# Generated by Django 5.2 on 2025-04-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='rejected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
