# Generated by Django 5.2 on 2025-04-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0003_appointments_rejected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
