# Generated by Django 5.2 on 2025-04-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0005_appointments_doctor_alter_appointments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='doctor',
            new_name='doctor_selected',
        ),
    ]
