# Generated by Django 5.2 on 2025-04-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0006_rename_doctor_appointments_doctor_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='rejected',
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
