# Generated by Django 5.2 on 2025-04-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0009_notification_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='accepted_date',
            new_name='status_date',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='rejected_date',
        ),
    ]
