# Generated by Django 5.2 on 2025-04-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0010_rename_accepted_date_appointments_status_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
