# Generated by Django 5.2 on 2025-04-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0011_appointments_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='call_requested',
            field=models.BooleanField(default=False),
        ),
    ]
