# Generated by Django 5.2 on 2025-04-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0013_appointments_call_room_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted(ongoing)'), ('rejected', 'Rejected'), ('ended', 'Ended')], default='pending', max_length=10),
        ),
    ]
