# Generated by Django 5.2 on 2025-05-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0014_alter_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='payment',
            field=models.CharField(choices=[('High', 'Premium'), ('Mid', 'Standard'), ('Low', 'Basic')], max_length=10, null=True),
        ),
    ]
