# Generated by Django 5.2 on 2025-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0015_appointments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='payment',
            field=models.CharField(choices=[('Premium', 'N10000'), ('Standard', 'Standard'), ('Basic', 'Basic')], max_length=10, null=True),
        ),
    ]
