# Generated by Django 5.2 on 2025-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0017_appointments_amount_alter_appointments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='payment',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('basic', 'Basic')], max_length=8, null=True),
        ),
    ]
