# Generated by Django 5.2 on 2025-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0019_appointments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='made_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
