# Generated by Django 5.2 on 2025-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0020_appointments_made_payment_alter_appointments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='voice_call_payment',
            field=models.BooleanField(default=False),
        ),
    ]
