# Generated by Django 5.2 on 2025-05-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0021_appointments_voice_call_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='voice_call_payment',
            new_name='video_call_payment',
        ),
    ]
